### ISSUE TITLE
Library management

### ISSUE THREAD

**Issue by st0012** [goby-lang/goby#78]
- Library in Goby is called `package`
- There should be `GOBY_PATH` for third-party packages and `GOBY_ROOT` for standard packages
- User's use `packages.yml` to specify the **github repo** and **commit sha** of required packages
  - We should create a new ticket for this
- There would be three kinds of libraries:
  - [ ] Third-party packages written in goby
  - [ ]  Standard packages written in goby
  - [x] Standard packages written in go

TBD:
- How to write tests for require mechanism 
~~Package lookup rule~~ (not for now)

**Comment by adlerhsieh** [comment]
Some ideas:

- Every rooby project has a `vendor` directory, which we read dependencies from.
- Every rooby project should use a `packages.yml` (basically like `Gemfile` in Ruby) to specify which dependency it is looking for and which source it is downloading from. It may look like this:

```yml
dependencies:
  - name: "foo"
    github: "rooby-lang/foo"
  - name: "bar"
    git: "git://some.url.git"
```

- As above, we can start from supporting GitHub (maybe other git sources).
- Hosting a package should always include a `spec.yml` to specify which package is this and which file to include. Something like:

```yml
name: "foo"
require: "./foo.ro"
dependencies:
  - name: "bar"
    github: "rooby-lang/bar"
```

- Requiring standard libraries are required the same way as requiring third-party packages. The difference is that it looks for a variable like `ROOBY_PATH` in env first before going into `vendor` directory. In `ROOBY_PATH` there are all built-in libraries but not required yet. For example, `json` and `yaml` libraries are installed along with the language but need to require.
